# Site settings
title: תיקון ושיפוץ חרוזים [localhost]
tag_text: תיקון ושיפוץ חרוזים
description: (בבית הלקוח? לא להגזים)

# Build settings
markdown: kramdown

exclude: ["README.md"]

collections:
  sections:
    output: false
